version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/phucnguyenit/circle-ci

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Get dependencies
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Build
          command: |
            go build -v
  release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
      
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
